backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "sayfa"
    label: "Sayfa İçeriği"
    files:
      - file: "index.html"
        label: "Ana Sayfa"
        name: "index"
        fields:
          - {label: "Başlık", name: "hero_title", widget: "string"}
          - {label: "Açıklama", name: "hero_desc", widget: "text"}
          - {label: "Ana Görsel", name: "hero_image", widget: "image"}